### PR TITLE
Update to 0.10

### PR DESCRIPTION
**Pull request by philip-khor**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philip-khor** [comment]
@conda-forge-admin, please rerender

**Comment by philip-khor** [comment]
@conda-forge/r-xfun PR ready for review, thanks!

**Comment by dbast** [comment]
Can we keep this open for some days? (If not then other packages will also proof the bot receives better information)

Reason is:
* https://github.com/regro/cf-scripts/pull/630
* https://github.com/regro/cf-scripts/pull/634
* https://github.com/librariesio/libraries.io/issues/2441

Maybe that gets merged/fixed and the bot proposes a xfun update :)

**Comment by philip-khor** [comment]
> 
> 
> Can we keep this open for some days? (If not then other packages will also proof the bot receives better information)
> 
> Reason is:
> 
>     * [regro/cf-scripts#630](https://github.com/regro/cf-scripts/pull/630)
> 
>     * [regro/cf-scripts#634](https://github.com/regro/cf-scripts/pull/634)
> 
>     * [librariesio/libraries.io#2441](https://github.com/librariesio/libraries.io/issues/2441)
> 
> 
> Maybe that gets merged/fixed and the bot proposes a xfun update :)

sure!

**Comment by dbast** [comment]
The bot got updated and arrived https://github.com/conda-forge/r-xfun-feedstock/pull/15 :)

Merging this as it contains more updates.

**Review by dbast — APPROVED** [review]

**Pull request merged**
