### PR TITLE
Enable OSX-arm

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #36.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge/r Any one have a clue why this didn't get build on osx-arm last time?

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
Good catch @xhochy !

**Pull request merged**
